# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.payout_response_dto import PayoutResponseDto

class TestPayoutResponseDto(unittest.TestCase):
    """PayoutResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutResponseDto:
        """Test PayoutResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutResponseDto`
        """
        model = PayoutResponseDto()
        if include_optional:
            return PayoutResponseDto(
                id = '',
                merchant_id = '',
                amount = 1.337,
                currency = '',
                status = '',
                bank_account = '',
                description = '',
                metadata = {"orderId":"12345"},
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PayoutResponseDto(
                id = '',
                merchant_id = '',
                amount = 1.337,
                currency = '',
                status = '',
                metadata = {"orderId":"12345"},
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPayoutResponseDto(self):
        """Test PayoutResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
