# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.reject_invitation_dto import RejectInvitationDto

class TestRejectInvitationDto(unittest.TestCase):
    """RejectInvitationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RejectInvitationDto:
        """Test RejectInvitationDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RejectInvitationDto`
        """
        model = RejectInvitationDto()
        if include_optional:
            return RejectInvitationDto(
                invitation_id = 'inv_12345'
            )
        else:
            return RejectInvitationDto(
                invitation_id = 'inv_12345',
        )
        """

    def testRejectInvitationDto(self):
        """Test RejectInvitationDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
