# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.checkout_session_confirm_response_dto import CheckoutSessionConfirmResponseDto

class TestCheckoutSessionConfirmResponseDto(unittest.TestCase):
    """CheckoutSessionConfirmResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckoutSessionConfirmResponseDto:
        """Test CheckoutSessionConfirmResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckoutSessionConfirmResponseDto`
        """
        model = CheckoutSessionConfirmResponseDto()
        if include_optional:
            return CheckoutSessionConfirmResponseDto(
                session_id = '',
                payment_intent_id = '',
                iveri_params = None,
                i_veri3ds_endpoint = ''
            )
        else:
            return CheckoutSessionConfirmResponseDto(
                session_id = '',
                payment_intent_id = '',
                iveri_params = None,
                i_veri3ds_endpoint = '',
        )
        """

    def testCheckoutSessionConfirmResponseDto(self):
        """Test CheckoutSessionConfirmResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
