# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.refresh_token_dto import RefreshTokenDto

class TestRefreshTokenDto(unittest.TestCase):
    """RefreshTokenDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefreshTokenDto:
        """Test RefreshTokenDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefreshTokenDto`
        """
        model = RefreshTokenDto()
        if include_optional:
            return RefreshTokenDto(
                refresh_token = 'refresh_token_123',
                rotate = True
            )
        else:
            return RefreshTokenDto(
                refresh_token = 'refresh_token_123',
        )
        """

    def testRefreshTokenDto(self):
        """Test RefreshTokenDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
