# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.invite_member_response_dto import InviteMemberResponseDto

class TestInviteMemberResponseDto(unittest.TestCase):
    """InviteMemberResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteMemberResponseDto:
        """Test InviteMemberResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteMemberResponseDto`
        """
        model = InviteMemberResponseDto()
        if include_optional:
            return InviteMemberResponseDto(
                invitation = {"id":"inv_123","email":"member@example.com"}
            )
        else:
            return InviteMemberResponseDto(
                invitation = {"id":"inv_123","email":"member@example.com"},
        )
        """

    def testInviteMemberResponseDto(self):
        """Test InviteMemberResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
