# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.analytics_summary_dto import AnalyticsSummaryDto

class TestAnalyticsSummaryDto(unittest.TestCase):
    """AnalyticsSummaryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsSummaryDto:
        """Test AnalyticsSummaryDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsSummaryDto`
        """
        model = AnalyticsSummaryDto()
        if include_optional:
            return AnalyticsSummaryDto(
                balance = 1.337,
                customers = 1.337,
                transactions = 1.337,
                members = 1.337
            )
        else:
            return AnalyticsSummaryDto(
                balance = 1.337,
                customers = 1.337,
                transactions = 1.337,
                members = 1.337,
        )
        """

    def testAnalyticsSummaryDto(self):
        """Test AnalyticsSummaryDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
