# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.payment_intents_api import PaymentIntentsApi


class TestPaymentIntentsApi(unittest.TestCase):
    """PaymentIntentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentIntentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_payment_intent(self) -> None:
        """Test case for cancel_payment_intent

        Cancel Payment Intent
        """
        pass

    def test_confirm_payment_intent(self) -> None:
        """Test case for confirm_payment_intent

        Confirm Payment Intent
        """
        pass

    def test_create_payment_intent(self) -> None:
        """Test case for create_payment_intent

        Create Payment Intent
        """
        pass

    def test_list_payment_intents(self) -> None:
        """Test case for list_payment_intents

        List Payment Intents
        """
        pass

    def test_retrieve_payment_intent(self) -> None:
        """Test case for retrieve_payment_intent

        Retrieve Payment Intent
        """
        pass


if __name__ == '__main__':
    unittest.main()
