# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.internal_analytics_insights_dto import InternalAnalyticsInsightsDto

class TestInternalAnalyticsInsightsDto(unittest.TestCase):
    """InternalAnalyticsInsightsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalAnalyticsInsightsDto:
        """Test InternalAnalyticsInsightsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalAnalyticsInsightsDto`
        """
        model = InternalAnalyticsInsightsDto()
        if include_optional:
            return InternalAnalyticsInsightsDto(
                organizations = 1.337,
                customers = 1.337,
                saved_payment_methods = 1.337,
                transactions = 1.337,
                total_available_balance = 1.337,
                total_pending_balance = 1.337
            )
        else:
            return InternalAnalyticsInsightsDto(
                organizations = 1.337,
                customers = 1.337,
                saved_payment_methods = 1.337,
                transactions = 1.337,
                total_available_balance = 1.337,
                total_pending_balance = 1.337,
        )
        """

    def testInternalAnalyticsInsightsDto(self):
        """Test InternalAnalyticsInsightsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
