# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.create_organization_dto import CreateOrganizationDto

class TestCreateOrganizationDto(unittest.TestCase):
    """CreateOrganizationDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrganizationDto:
        """Test CreateOrganizationDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrganizationDto`
        """
        model = CreateOrganizationDto()
        if include_optional:
            return CreateOrganizationDto(
                name = 'Acme Corp',
                slug = 'acme-corp',
                logo = 'https://example.com/logo.png',
                metadata = {"plan":"pro"}
            )
        else:
            return CreateOrganizationDto(
                name = 'Acme Corp',
                slug = 'acme-corp',
        )
        """

    def testCreateOrganizationDto(self):
        """Test CreateOrganizationDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
