# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.bulk_ids_dto import BulkIdsDto

class TestBulkIdsDto(unittest.TestCase):
    """BulkIdsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkIdsDto:
        """Test BulkIdsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkIdsDto`
        """
        model = BulkIdsDto()
        if include_optional:
            return BulkIdsDto(
                ids = ["id_1","id_2"]
            )
        else:
            return BulkIdsDto(
                ids = ["id_1","id_2"],
        )
        """

    def testBulkIdsDto(self):
        """Test BulkIdsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
