# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.send_verification_email_dto import SendVerificationEmailDto

class TestSendVerificationEmailDto(unittest.TestCase):
    """SendVerificationEmailDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendVerificationEmailDto:
        """Test SendVerificationEmailDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendVerificationEmailDto`
        """
        model = SendVerificationEmailDto()
        if include_optional:
            return SendVerificationEmailDto(
                email = 'user@example.com',
                callback_url = 'https://example.com/callback'
            )
        else:
            return SendVerificationEmailDto(
                email = 'user@example.com',
        )
        """

    def testSendVerificationEmailDto(self):
        """Test SendVerificationEmailDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
