# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.update_checkout_session_dto import UpdateCheckoutSessionDto

class TestUpdateCheckoutSessionDto(unittest.TestCase):
    """UpdateCheckoutSessionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCheckoutSessionDto:
        """Test UpdateCheckoutSessionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCheckoutSessionDto`
        """
        model = UpdateCheckoutSessionDto()
        if include_optional:
            return UpdateCheckoutSessionDto(
                status = '',
                success_url = '',
                failure_url = '',
                cancel_url = '',
                metadata = {"orderId":"ORD-12345"},
                hosted_checkout_config = cashful.models.hosted_checkout_config_dto.HostedCheckoutConfigDto(
                    merchant_id = '', 
                    merchant_alias = '', 
                    merchant_legal_name = '', 
                    merchant_avatar_text_placeholder = '', 
                    merchant_avatar_url = '', 
                    require_contact = True, 
                    require_address = True, 
                    tax_rate = 1.337, 
                    embed_mode = True, 
                    embed_origin = '', )
            )
        else:
            return UpdateCheckoutSessionDto(
                status = '',
                metadata = {"orderId":"ORD-12345"},
        )
        """

    def testUpdateCheckoutSessionDto(self):
        """Test UpdateCheckoutSessionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
