# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.unlink_account_response_dto import UnlinkAccountResponseDto

class TestUnlinkAccountResponseDto(unittest.TestCase):
    """UnlinkAccountResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnlinkAccountResponseDto:
        """Test UnlinkAccountResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnlinkAccountResponseDto`
        """
        model = UnlinkAccountResponseDto()
        if include_optional:
            return UnlinkAccountResponseDto(
                success = True
            )
        else:
            return UnlinkAccountResponseDto(
                success = True,
        )
        """

    def testUnlinkAccountResponseDto(self):
        """Test UnlinkAccountResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
