# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.impersonate_user_dto import ImpersonateUserDto

class TestImpersonateUserDto(unittest.TestCase):
    """ImpersonateUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImpersonateUserDto:
        """Test ImpersonateUserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImpersonateUserDto`
        """
        model = ImpersonateUserDto()
        if include_optional:
            return ImpersonateUserDto(
                user_id = 'user_12345'
            )
        else:
            return ImpersonateUserDto(
                user_id = 'user_12345',
        )
        """

    def testImpersonateUserDto(self):
        """Test ImpersonateUserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
