# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.2
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.verify_api_key_response_dto import VerifyApiKeyResponseDto

class TestVerifyApiKeyResponseDto(unittest.TestCase):
    """VerifyApiKeyResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyApiKeyResponseDto:
        """Test VerifyApiKeyResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyApiKeyResponseDto`
        """
        model = VerifyApiKeyResponseDto()
        if include_optional:
            return VerifyApiKeyResponseDto(
                valid = False,
                key = {"id":"key_123","name":"My API Key"}
            )
        else:
            return VerifyApiKeyResponseDto(
                valid = False,
        )
        """

    def testVerifyApiKeyResponseDto(self):
        """Test VerifyApiKeyResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
