# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.compliance_api import ComplianceApi


class TestComplianceApi(unittest.TestCase):
    """ComplianceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ComplianceApi()

    def tearDown(self) -> None:
        pass

    def test_create_compliance(self) -> None:
        """Test case for create_compliance

        Create Compliance info
        """
        pass

    def test_get_compliance(self) -> None:
        """Test case for get_compliance

        Get Compliance info for organization
        """
        pass

    def test_update_compliance(self) -> None:
        """Test case for update_compliance

        Update Compliance info
        """
        pass


if __name__ == '__main__':
    unittest.main()
