# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_get_analytics(self) -> None:
        """Test case for get_analytics

        Get Analytics
        """
        pass

    def test_get_analytics_summary(self) -> None:
        """Test case for get_analytics_summary

        Get Analytics Summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
