# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.list_products_response_dto import ListProductsResponseDto

class TestListProductsResponseDto(unittest.TestCase):
    """ListProductsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProductsResponseDto:
        """Test ListProductsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProductsResponseDto`
        """
        model = ListProductsResponseDto()
        if include_optional:
            return ListProductsResponseDto(
                data = [
                    cashful.models.product_response_dto.ProductResponseDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        merchant_id = '', 
                        name = '', 
                        description = '', 
                        amount = 1.337, 
                        currency = '', 
                        active = True, 
                        image_id = '', 
                        image_url = '', 
                        metadata = {"sku":"PROD-001"}, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, )
            )
        else:
            return ListProductsResponseDto(
                data = [
                    cashful.models.product_response_dto.ProductResponseDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        merchant_id = '', 
                        name = '', 
                        description = '', 
                        amount = 1.337, 
                        currency = '', 
                        active = True, 
                        image_id = '', 
                        image_url = '', 
                        metadata = {"sku":"PROD-001"}, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, ),
        )
        """

    def testListProductsResponseDto(self):
        """Test ListProductsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
