# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.list_payment_methods_response_dto import ListPaymentMethodsResponseDto

class TestListPaymentMethodsResponseDto(unittest.TestCase):
    """ListPaymentMethodsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPaymentMethodsResponseDto:
        """Test ListPaymentMethodsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPaymentMethodsResponseDto`
        """
        model = ListPaymentMethodsResponseDto()
        if include_optional:
            return ListPaymentMethodsResponseDto(
                data = [
                    cashful.models.payment_method_response_dto.PaymentMethodResponseDto(
                        id = '', 
                        customer_id = '', 
                        type = '', 
                        provider = '', 
                        brand = '', 
                        last4 = '', 
                        expiry_month = 1.337, 
                        expiry_year = 1.337, 
                        phone_number = '', 
                        is_default = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, )
            )
        else:
            return ListPaymentMethodsResponseDto(
                data = [
                    cashful.models.payment_method_response_dto.PaymentMethodResponseDto(
                        id = '', 
                        customer_id = '', 
                        type = '', 
                        provider = '', 
                        brand = '', 
                        last4 = '', 
                        expiry_month = 1.337, 
                        expiry_year = 1.337, 
                        phone_number = '', 
                        is_default = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, ),
        )
        """

    def testListPaymentMethodsResponseDto(self):
        """Test ListPaymentMethodsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
