# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.storage_api import StorageApi


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageApi()

    def tearDown(self) -> None:
        pass

    def test_confirm_upload(self) -> None:
        """Test case for confirm_upload

        Confirm that a file upload was completed
        """
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        Delete a file
        """
        pass

    def test_get_download_url(self) -> None:
        """Test case for get_download_url

        Get a presigned download URL for a file
        """
        pass

    def test_get_file_details(self) -> None:
        """Test case for get_file_details

        Get file details
        """
        pass

    def test_list_files(self) -> None:
        """Test case for list_files

        List files
        """
        pass

    def test_request_upload_url(self) -> None:
        """Test case for request_upload_url

        Request a presigned URL for file upload
        """
        pass


if __name__ == '__main__':
    unittest.main()
