# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.update_member_role_dto import UpdateMemberRoleDto

class TestUpdateMemberRoleDto(unittest.TestCase):
    """UpdateMemberRoleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateMemberRoleDto:
        """Test UpdateMemberRoleDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateMemberRoleDto`
        """
        model = UpdateMemberRoleDto()
        if include_optional:
            return UpdateMemberRoleDto(
                member_id = 'mem_12345',
                role = 'admin',
                organization_id = 'org_12345'
            )
        else:
            return UpdateMemberRoleDto(
                member_id = 'mem_12345',
                role = 'admin',
                organization_id = 'org_12345',
        )
        """

    def testUpdateMemberRoleDto(self):
        """Test UpdateMemberRoleDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
