# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.list_event_types_response_dto import ListEventTypesResponseDto

class TestListEventTypesResponseDto(unittest.TestCase):
    """ListEventTypesResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListEventTypesResponseDto:
        """Test ListEventTypesResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListEventTypesResponseDto`
        """
        model = ListEventTypesResponseDto()
        if include_optional:
            return ListEventTypesResponseDto(
                data = [
                    cashful.models.event_type_response_dto.EventTypeResponseDto(
                        id = '', 
                        name = '', 
                        description = '', 
                        is_active = True, )
                    ]
            )
        else:
            return ListEventTypesResponseDto(
                data = [
                    cashful.models.event_type_response_dto.EventTypeResponseDto(
                        id = '', 
                        name = '', 
                        description = '', 
                        is_active = True, )
                    ],
        )
        """

    def testListEventTypesResponseDto(self):
        """Test ListEventTypesResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
