# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.link_social_response_dto import LinkSocialResponseDto

class TestLinkSocialResponseDto(unittest.TestCase):
    """LinkSocialResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkSocialResponseDto:
        """Test LinkSocialResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkSocialResponseDto`
        """
        model = LinkSocialResponseDto()
        if include_optional:
            return LinkSocialResponseDto(
                success = True,
                account = None
            )
        else:
            return LinkSocialResponseDto(
                success = True,
        )
        """

    def testLinkSocialResponseDto(self):
        """Test LinkSocialResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
