# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.send_multi_channel_notification200_response import SendMultiChannelNotification200Response

class TestSendMultiChannelNotification200Response(unittest.TestCase):
    """SendMultiChannelNotification200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMultiChannelNotification200Response:
        """Test SendMultiChannelNotification200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMultiChannelNotification200Response`
        """
        model = SendMultiChannelNotification200Response()
        if include_optional:
            return SendMultiChannelNotification200Response(
                email = '',
                sms = ''
            )
        else:
            return SendMultiChannelNotification200Response(
        )
        """

    def testSendMultiChannelNotification200Response(self):
        """Test SendMultiChannelNotification200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
