# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.line_item_dto import LineItemDto

class TestLineItemDto(unittest.TestCase):
    """LineItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LineItemDto:
        """Test LineItemDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LineItemDto`
        """
        model = LineItemDto()
        if include_optional:
            return LineItemDto(
                product_id = '',
                quantity = 1.337,
                amount = 1.337,
                currency = ''
            )
        else:
            return LineItemDto(
                amount = 1.337,
                currency = '',
        )
        """

    def testLineItemDto(self):
        """Test LineItemDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
