# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.debit_return_response_dto import DebitReturnResponseDto

class TestDebitReturnResponseDto(unittest.TestCase):
    """DebitReturnResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebitReturnResponseDto:
        """Test DebitReturnResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebitReturnResponseDto`
        """
        model = DebitReturnResponseDto()
        if include_optional:
            return DebitReturnResponseDto(
                status = 'succeeded',
                merchant_reference = 'pi_xyz789',
                payment_intent_id = 'pi_xyz789',
                transaction_id = 'txn_abc123',
                auth_code = 'AUTH123456',
                reason = 'Insufficient funds',
                amount = 10000,
                currency = 'ZAR'
            )
        else:
            return DebitReturnResponseDto(
                status = 'succeeded',
                merchant_reference = 'pi_xyz789',
        )
        """

    def testDebitReturnResponseDto(self):
        """Test DebitReturnResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
