# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.timeframe_metrics_dto import TimeframeMetricsDto

class TestTimeframeMetricsDto(unittest.TestCase):
    """TimeframeMetricsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeframeMetricsDto:
        """Test TimeframeMetricsDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeframeMetricsDto`
        """
        model = TimeframeMetricsDto()
        if include_optional:
            return TimeframeMetricsDto(
                daily = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                weekly = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                monthly = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                breakdown = [
                    cashful.models.daily_breakdown_dto.DailyBreakdownDto(
                        date = '', 
                        count = 1.337, 
                        sum = 1.337, )
                    ]
            )
        else:
            return TimeframeMetricsDto(
                daily = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                weekly = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                monthly = cashful.models.metric_stats_dto.MetricStatsDto(
                    count = 1.337, 
                    sum = 1.337, ),
                breakdown = [
                    cashful.models.daily_breakdown_dto.DailyBreakdownDto(
                        date = '', 
                        count = 1.337, 
                        sum = 1.337, )
                    ],
        )
        """

    def testTimeframeMetricsDto(self):
        """Test TimeframeMetricsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
