# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.create_checkout_session_dto import CreateCheckoutSessionDto

class TestCreateCheckoutSessionDto(unittest.TestCase):
    """CreateCheckoutSessionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCheckoutSessionDto:
        """Test CreateCheckoutSessionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCheckoutSessionDto`
        """
        model = CreateCheckoutSessionDto()
        if include_optional:
            return CreateCheckoutSessionDto(
                merchant_id = '',
                customer_id = '',
                product_id = '',
                success_url = '',
                cancel_url = '',
                line_items = [
                    cashful.models.line_item_dto.LineItemDto(
                        name = '', 
                        product_id = '', 
                        quantity = 1.337, 
                        amount = 1.337, 
                        currency = '', 
                        image_id = '', 
                        image_url = '', )
                    ],
                total_amount = 1.337,
                currency = '',
                mode = '',
                metadata = {"orderId":"ORD-12345","source":"web"},
                hosted_checkout_config = cashful.models.hosted_checkout_config_dto.HostedCheckoutConfigDto(
                    merchant_id = '', 
                    merchant_alias = '', 
                    merchant_legal_name = '', 
                    merchant_avatar_text_placeholder = '', 
                    merchant_avatar_url = '', 
                    require_contact = True, 
                    require_address = True, 
                    tax_rate = 1.337, 
                    embed_mode = True, 
                    embed_origin = '', 
                    methods = [
                        'card'
                        ], )
            )
        else:
            return CreateCheckoutSessionDto(
                merchant_id = '',
                currency = '',
                metadata = {"orderId":"ORD-12345","source":"web"},
        )
        """

    def testCreateCheckoutSessionDto(self):
        """Test CreateCheckoutSessionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
