# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        Send an email notification
        """
        pass

    def test_send_multi_channel_notification(self) -> None:
        """Test case for send_multi_channel_notification

        Send notifications via multiple channels
        """
        pass

    def test_send_notification(self) -> None:
        """Test case for send_notification

        Send a notification via specified channel
        """
        pass

    def test_send_sms(self) -> None:
        """Test case for send_sms

        Send an SMS notification
        """
        pass


if __name__ == '__main__':
    unittest.main()
