# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.verify_phone_number_response_dto import VerifyPhoneNumberResponseDto

class TestVerifyPhoneNumberResponseDto(unittest.TestCase):
    """VerifyPhoneNumberResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyPhoneNumberResponseDto:
        """Test VerifyPhoneNumberResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyPhoneNumberResponseDto`
        """
        model = VerifyPhoneNumberResponseDto()
        if include_optional:
            return VerifyPhoneNumberResponseDto(
                success = True,
                user = cashful.models.session_user_dto.SessionUserDto(
                    id = '', 
                    email = '', 
                    email_verified = True, 
                    name = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return VerifyPhoneNumberResponseDto(
                success = True,
        )
        """

    def testVerifyPhoneNumberResponseDto(self):
        """Test VerifyPhoneNumberResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
