# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.sign_up_dto import SignUpDto

class TestSignUpDto(unittest.TestCase):
    """SignUpDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignUpDto:
        """Test SignUpDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignUpDto`
        """
        model = SignUpDto()
        if include_optional:
            return SignUpDto(
                name = 'John Doe',
                email = 'john.doe@example.com',
                password = 'StrongPassword123!',
                image = 'https://example.com/avatar.jpg',
                callback_url = 'https://example.com/auth/callback',
                remember_me = True
            )
        else:
            return SignUpDto(
                name = 'John Doe',
                email = 'john.doe@example.com',
                password = 'StrongPassword123!',
        )
        """

    def testSignUpDto(self):
        """Test SignUpDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
