# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_create_event(self) -> None:
        """Test case for create_event

        Create Event
        """
        pass

    def test_list_event_types(self) -> None:
        """Test case for list_event_types

        List Event Types
        """
        pass

    def test_list_events(self) -> None:
        """Test case for list_events

        List Events
        """
        pass


if __name__ == '__main__':
    unittest.main()
