# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.request_upload_url_dto import RequestUploadUrlDto

class TestRequestUploadUrlDto(unittest.TestCase):
    """RequestUploadUrlDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUploadUrlDto:
        """Test RequestUploadUrlDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUploadUrlDto`
        """
        model = RequestUploadUrlDto()
        if include_optional:
            return RequestUploadUrlDto(
                filename = '',
                mime_type = 'image/png',
                tags = ["compliance","identity-document"],
                related_entity_id = '',
                related_entity_type = ''
            )
        else:
            return RequestUploadUrlDto(
                filename = '',
                mime_type = 'image/png',
        )
        """

    def testRequestUploadUrlDto(self):
        """Test RequestUploadUrlDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
