# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.list_checkout_sessions_response_dto import ListCheckoutSessionsResponseDto

class TestListCheckoutSessionsResponseDto(unittest.TestCase):
    """ListCheckoutSessionsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCheckoutSessionsResponseDto:
        """Test ListCheckoutSessionsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCheckoutSessionsResponseDto`
        """
        model = ListCheckoutSessionsResponseDto()
        if include_optional:
            return ListCheckoutSessionsResponseDto(
                data = [
                    cashful.models.checkout_session_response_dto.CheckoutSessionResponseDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        merchant_id = '', 
                        customer_id = '', 
                        session_url = '', 
                        success_url = '', 
                        cancel_url = '', 
                        line_items = [
                            cashful.models.line_item_dto.LineItemDto(
                                product_id = '', 
                                quantity = 1.337, 
                                amount = 1.337, 
                                currency = '', )
                            ], 
                        total_amount = 1.337, 
                        currency = '', 
                        mode = '', 
                        status = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = {"orderId":"ORD-12345"}, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, )
            )
        else:
            return ListCheckoutSessionsResponseDto(
                data = [
                    cashful.models.checkout_session_response_dto.CheckoutSessionResponseDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        merchant_id = '', 
                        customer_id = '', 
                        session_url = '', 
                        success_url = '', 
                        cancel_url = '', 
                        line_items = [
                            cashful.models.line_item_dto.LineItemDto(
                                product_id = '', 
                                quantity = 1.337, 
                                amount = 1.337, 
                                currency = '', )
                            ], 
                        total_amount = 1.337, 
                        currency = '', 
                        mode = '', 
                        status = '', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = {"orderId":"ORD-12345"}, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, ),
        )
        """

    def testListCheckoutSessionsResponseDto(self):
        """Test ListCheckoutSessionsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
