# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.unban_user_response_dto import UnbanUserResponseDto

class TestUnbanUserResponseDto(unittest.TestCase):
    """UnbanUserResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnbanUserResponseDto:
        """Test UnbanUserResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnbanUserResponseDto`
        """
        model = UnbanUserResponseDto()
        if include_optional:
            return UnbanUserResponseDto(
                success = False
            )
        else:
            return UnbanUserResponseDto(
                success = False,
        )
        """

    def testUnbanUserResponseDto(self):
        """Test UnbanUserResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
