# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.presigned_download_response_dto import PresignedDownloadResponseDto

class TestPresignedDownloadResponseDto(unittest.TestCase):
    """PresignedDownloadResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PresignedDownloadResponseDto:
        """Test PresignedDownloadResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PresignedDownloadResponseDto`
        """
        model = PresignedDownloadResponseDto()
        if include_optional:
            return PresignedDownloadResponseDto(
                download_url = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PresignedDownloadResponseDto(
                download_url = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPresignedDownloadResponseDto(self):
        """Test PresignedDownloadResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
