# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.2
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.send_email_dto import SendEmailDto

class TestSendEmailDto(unittest.TestCase):
    """SendEmailDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailDto:
        """Test SendEmailDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailDto`
        """
        model = SendEmailDto()
        if include_optional:
            return SendEmailDto(
                to = user@example.com,
                subject = 'Welcome to Cashful',
                template = 'welcome',
                context = {"name":"John Doe","activationLink":"https://example.com/activate"},
                html = '<p>Hello World</p>',
                text = 'Hello World',
                var_from = 'noreply@cashful.africa',
                cc = ["admin@cashful.africa"],
                bcc = ["archive@cashful.africa"]
            )
        else:
            return SendEmailDto(
                to = user@example.com,
                subject = 'Welcome to Cashful',
        )
        """

    def testSendEmailDto(self):
        """Test SendEmailDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
