# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.confirm_payment_intent_dto import ConfirmPaymentIntentDto

class TestConfirmPaymentIntentDto(unittest.TestCase):
    """ConfirmPaymentIntentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfirmPaymentIntentDto:
        """Test ConfirmPaymentIntentDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfirmPaymentIntentDto`
        """
        model = ConfirmPaymentIntentDto()
        if include_optional:
            return ConfirmPaymentIntentDto(
                evervault_encrypted_card = cashful.models.evervault_encrypted_card_dto.EvervaultEncryptedCardDto(
                    p_an = 'ev:encrypted:ABC123...', 
                    expiry_date = 'ev:encrypted:DEF456...', 
                    card_security_code = 'ev:encrypted:GHI789...', 
                    cardholder_name = 'ev:encrypted:JKL012...', ),
                masked_pan = '',
                tokenize_card = True,
                first_name = '',
                last_name = '',
                phone_number = '',
                payment_description = '',
                merchant_name = '',
                metadata = { }
            )
        else:
            return ConfirmPaymentIntentDto(
                evervault_encrypted_card = cashful.models.evervault_encrypted_card_dto.EvervaultEncryptedCardDto(
                    p_an = 'ev:encrypted:ABC123...', 
                    expiry_date = 'ev:encrypted:DEF456...', 
                    card_security_code = 'ev:encrypted:GHI789...', 
                    cardholder_name = 'ev:encrypted:JKL012...', ),
        )
        """

    def testConfirmPaymentIntentDto(self):
        """Test ConfirmPaymentIntentDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
