# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.request_password_reset_response_dto import RequestPasswordResetResponseDto

class TestRequestPasswordResetResponseDto(unittest.TestCase):
    """RequestPasswordResetResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestPasswordResetResponseDto:
        """Test RequestPasswordResetResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestPasswordResetResponseDto`
        """
        model = RequestPasswordResetResponseDto()
        if include_optional:
            return RequestPasswordResetResponseDto(
                status = True,
                message = 'Password reset email sent'
            )
        else:
            return RequestPasswordResetResponseDto(
                status = True,
        )
        """

    def testRequestPasswordResetResponseDto(self):
        """Test RequestPasswordResetResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
