# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer(self) -> None:
        """Test case for create_customer

        Create Customer
        """
        pass

    def test_get_customer_balance(self) -> None:
        """Test case for get_customer_balance

        Get Customer's Cash Balance
        """
        pass

    def test_list_customer_payment_methods(self) -> None:
        """Test case for list_customer_payment_methods

        List Customer's Payment Methods
        """
        pass

    def test_list_customer_transactions(self) -> None:
        """Test case for list_customer_transactions

        List Customer's Cash Transactions
        """
        pass

    def test_list_customers(self) -> None:
        """Test case for list_customers

        List Customers
        """
        pass

    def test_retrieve_customer(self) -> None:
        """Test case for retrieve_customer

        Retrieve Customer
        """
        pass

    def test_update_customer(self) -> None:
        """Test case for update_customer

        Update Customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
