# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.list_customer_transactions_response_dto import ListCustomerTransactionsResponseDto

class TestListCustomerTransactionsResponseDto(unittest.TestCase):
    """ListCustomerTransactionsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCustomerTransactionsResponseDto:
        """Test ListCustomerTransactionsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCustomerTransactionsResponseDto`
        """
        model = ListCustomerTransactionsResponseDto()
        if include_optional:
            return ListCustomerTransactionsResponseDto(
                data = [
                    cashful.models.customer_transaction_dto.CustomerTransactionDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        customer_id = '', 
                        merchant_id = '', 
                        type = '', 
                        amount = 1.337, 
                        currency = '', 
                        description = '', 
                        related_entity_id = '', 
                        related_entity_type = '', 
                        balance_after = 1.337, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, )
            )
        else:
            return ListCustomerTransactionsResponseDto(
                data = [
                    cashful.models.customer_transaction_dto.CustomerTransactionDto(
                        id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        customer_id = '', 
                        merchant_id = '', 
                        type = '', 
                        amount = 1.337, 
                        currency = '', 
                        description = '', 
                        related_entity_id = '', 
                        related_entity_type = '', 
                        balance_after = 1.337, )
                    ],
                pagination = cashful.models.pagination_response_dto.PaginationResponseDto(
                    limit = 50, 
                    offset = 0, 
                    total = 150, 
                    has_more = True, ),
        )
        """

    def testListCustomerTransactionsResponseDto(self):
        """Test ListCustomerTransactionsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
