# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.request_password_reset_dto import RequestPasswordResetDto

class TestRequestPasswordResetDto(unittest.TestCase):
    """RequestPasswordResetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestPasswordResetDto:
        """Test RequestPasswordResetDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestPasswordResetDto`
        """
        model = RequestPasswordResetDto()
        if include_optional:
            return RequestPasswordResetDto(
                email = 'user@example.com',
                redirect_to = 'https://example.com/reset-password'
            )
        else:
            return RequestPasswordResetDto(
                email = 'user@example.com',
        )
        """

    def testRequestPasswordResetDto(self):
        """Test RequestPasswordResetDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
