# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.payment_link_response_dto import PaymentLinkResponseDto

class TestPaymentLinkResponseDto(unittest.TestCase):
    """PaymentLinkResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentLinkResponseDto:
        """Test PaymentLinkResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentLinkResponseDto`
        """
        model = PaymentLinkResponseDto()
        if include_optional:
            return PaymentLinkResponseDto(
                id = '',
                merchant_id = '',
                url = '',
                product_id = '',
                customer_id = '',
                amount = 1.337,
                currency = '',
                mode = 'payment',
                active = True,
                success_url = '',
                cancel_url = '',
                metadata = {"customField":"value"},
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PaymentLinkResponseDto(
                id = '',
                merchant_id = '',
                url = '',
                currency = '',
                mode = 'payment',
                active = True,
                success_url = '',
                cancel_url = '',
                metadata = {"customField":"value"},
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPaymentLinkResponseDto(self):
        """Test PaymentLinkResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
