# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.update_file_dto import UpdateFileDto

class TestUpdateFileDto(unittest.TestCase):
    """UpdateFileDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateFileDto:
        """Test UpdateFileDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateFileDto`
        """
        model = UpdateFileDto()
        if include_optional:
            return UpdateFileDto(
                tags = [
                    ''
                    ],
                status = 'pending',
                is_public = True,
                related_entity_id = '',
                related_entity_type = ''
            )
        else:
            return UpdateFileDto(
        )
        """

    def testUpdateFileDto(self):
        """Test UpdateFileDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
