# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.2
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.api.purchases_api import PurchasesApi


class TestPurchasesApi(unittest.TestCase):
    """PurchasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchasesApi()

    def tearDown(self) -> None:
        pass

    def test_create_purchase(self) -> None:
        """Test case for create_purchase

        Buy with Cash Balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
