# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.2
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.daily_breakdown_dto import DailyBreakdownDto

class TestDailyBreakdownDto(unittest.TestCase):
    """DailyBreakdownDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DailyBreakdownDto:
        """Test DailyBreakdownDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DailyBreakdownDto`
        """
        model = DailyBreakdownDto()
        if include_optional:
            return DailyBreakdownDto(
                var_date = '',
                count = 1.337,
                sum = 1.337
            )
        else:
            return DailyBreakdownDto(
                var_date = '',
                count = 1.337,
                sum = 1.337,
        )
        """

    def testDailyBreakdownDto(self):
        """Test DailyBreakdownDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
