# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.send_phone_otp_dto import SendPhoneOTPDto

class TestSendPhoneOTPDto(unittest.TestCase):
    """SendPhoneOTPDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendPhoneOTPDto:
        """Test SendPhoneOTPDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendPhoneOTPDto`
        """
        model = SendPhoneOTPDto()
        if include_optional:
            return SendPhoneOTPDto(
                phone_number = '+1234567890'
            )
        else:
            return SendPhoneOTPDto(
                phone_number = '+1234567890',
        )
        """

    def testSendPhoneOTPDto(self):
        """Test SendPhoneOTPDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
