# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.3
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cashful.models.reset_phone_password_response_dto import ResetPhonePasswordResponseDto

class TestResetPhonePasswordResponseDto(unittest.TestCase):
    """ResetPhonePasswordResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResetPhonePasswordResponseDto:
        """Test ResetPhonePasswordResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResetPhonePasswordResponseDto`
        """
        model = ResetPhonePasswordResponseDto()
        if include_optional:
            return ResetPhonePasswordResponseDto(
                success = True
            )
        else:
            return ResetPhonePasswordResponseDto(
                success = True,
        )
        """

    def testResetPhonePasswordResponseDto(self):
        """Test ResetPhonePasswordResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
