# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cashful.models.hosted_checkout_config_dto import HostedCheckoutConfigDto
from cashful.models.line_item_dto import LineItemDto
from typing import Optional, Set
from typing_extensions import Self

class CreateCheckoutSessionDto(BaseModel):
    """
    CreateCheckoutSessionDto
    """ # noqa: E501
    merchant_id: StrictStr = Field(description="The ID of the merchant for the checkout session.", alias="merchantId")
    customer_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the customer", alias="customerId")
    product_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the product", alias="productId")
    success_url: Optional[StrictStr] = Field(default=None, description="The URL to redirect to on successful payment", alias="successUrl")
    cancel_url: Optional[StrictStr] = Field(default=None, description="The URL to redirect to on cancel", alias="cancelUrl")
    line_items: Optional[List[LineItemDto]] = Field(default=None, description="Array of line items for the checkout", alias="lineItems")
    total_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The total amount in the smallest currency unit", alias="totalAmount")
    currency: StrictStr = Field(description="The three-letter ISO 4217 currency code")
    mode: Optional[StrictStr] = Field(default=None, description="The checkout mode (e.g., 'payment')")
    metadata: Dict[str, Any] = Field(description="Optional custom metadata")
    hosted_checkout_config: Optional[HostedCheckoutConfigDto] = Field(default=None, description="Configuration for the hosted checkout page", alias="hostedCheckoutConfig")
    __properties: ClassVar[List[str]] = ["merchantId", "customerId", "productId", "successUrl", "cancelUrl", "lineItems", "totalAmount", "currency", "mode", "metadata", "hostedCheckoutConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCheckoutSessionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item_line_items in self.line_items:
                if _item_line_items:
                    _items.append(_item_line_items.to_dict())
            _dict['lineItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of hosted_checkout_config
        if self.hosted_checkout_config:
            _dict['hostedCheckoutConfig'] = self.hosted_checkout_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCheckoutSessionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchantId": obj.get("merchantId"),
            "customerId": obj.get("customerId"),
            "productId": obj.get("productId"),
            "successUrl": obj.get("successUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "lineItems": [LineItemDto.from_dict(_item) for _item in obj["lineItems"]] if obj.get("lineItems") is not None else None,
            "totalAmount": obj.get("totalAmount"),
            "currency": obj.get("currency"),
            "mode": obj.get("mode"),
            "metadata": obj.get("metadata"),
            "hostedCheckoutConfig": HostedCheckoutConfigDto.from_dict(obj["hostedCheckoutConfig"]) if obj.get("hostedCheckoutConfig") is not None else None
        })
        return _obj


