# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreatePaymentIntentDto(BaseModel):
    """
    CreatePaymentIntentDto
    """ # noqa: E501
    merchant_id: Optional[StrictStr] = Field(default=None, description="The ID of the merchant whose balance is being requested. If omitted, defaults to the authenticated merchant.", alias="merchantId")
    customer_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the customer. Optional for payment intents that don't require a customer.", alias="customerId")
    payment_method_id: Optional[StrictStr] = Field(default=None, description="The unique identifier of the payment method. Optional if payment method will be collected later.", alias="paymentMethodId")
    amount: Union[StrictFloat, StrictInt] = Field(description="The amount to charge in the smallest currency unit (cents)")
    currency: StrictStr = Field(description="The three-letter ISO 4217 currency code")
    mode: Optional[StrictStr] = Field(default='payment', description="The mode of the payment intent")
    description: Optional[StrictStr] = Field(default=None, description="Optional description for the payment")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional custom metadata")
    idempotency_key: Optional[StrictStr] = Field(default=None, description="A unique key to prevent duplicate charges. If not provided, one will be generated.", alias="idempotencyKey")
    expires_at: Optional[datetime] = Field(default=None, description="When the payment intent expires. Defaults to 24 hours from creation.", alias="expiresAt")
    __properties: ClassVar[List[str]] = ["merchantId", "customerId", "paymentMethodId", "amount", "currency", "mode", "description", "metadata", "idempotencyKey", "expiresAt"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['payment', 'setup', 'subscription']):
            raise ValueError("must be one of enum values ('payment', 'setup', 'subscription')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePaymentIntentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePaymentIntentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchantId": obj.get("merchantId"),
            "customerId": obj.get("customerId"),
            "paymentMethodId": obj.get("paymentMethodId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "mode": obj.get("mode") if obj.get("mode") is not None else 'payment',
            "description": obj.get("description"),
            "metadata": obj.get("metadata"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "expiresAt": obj.get("expiresAt")
        })
        return _obj


