# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.4
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreateOrganizationComplianceDto(BaseModel):
    """
    CreateOrganizationComplianceDto
    """ # noqa: E501
    organization_id: StrictStr = Field(alias="organizationId")
    company_registration_name: Optional[StrictStr] = Field(default=None, alias="companyRegistrationName")
    company_registration_number: Optional[StrictStr] = Field(default=None, alias="companyRegistrationNumber")
    company_trading_name: Optional[StrictStr] = Field(default=None, alias="companyTradingName")
    vat_registration_number: Optional[StrictStr] = Field(default=None, alias="vatRegistrationNumber")
    industry: Optional[StrictStr] = None
    sub_industry: Optional[StrictStr] = Field(default=None, alias="subIndustry")
    estimated_annual_turnover: Optional[StrictStr] = Field(default=None, alias="estimatedAnnualTurnover")
    business_description: Optional[StrictStr] = Field(default=None, description="Long business description", alias="businessDescription")
    company_mobile_money_settlement_number: Optional[StrictStr] = Field(default=None, alias="companyMobileMoneySettlementNumber")
    company_email: Optional[StrictStr] = Field(default=None, alias="companyEmail")
    company_contact_number: Optional[StrictStr] = Field(default=None, alias="companyContactNumber")
    website: Optional[StrictStr] = None
    social_media: Optional[StrictStr] = Field(default=None, alias="socialMedia")
    account_contact_number: Optional[StrictStr] = Field(default=None, alias="accountContactNumber")
    customer_support_contact_number: Optional[StrictStr] = Field(default=None, alias="customerSupportContactNumber")
    customer_support_escalation_contact_number: Optional[StrictStr] = Field(default=None, alias="customerSupportEscalationContactNumber")
    emergency_contact_number: Optional[StrictStr] = Field(default=None, alias="emergencyContactNumber")
    street_address: Optional[StrictStr] = Field(default=None, alias="streetAddress")
    apartment: Optional[StrictStr] = None
    suburb: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    postal_code: Optional[StrictStr] = Field(default=None, alias="postalCode")
    country: Optional[StrictStr] = None
    bank: Optional[StrictStr] = None
    account_type: Optional[StrictStr] = Field(default=None, alias="accountType")
    account_name: Optional[StrictStr] = Field(default=None, alias="accountName")
    account_number: Optional[StrictStr] = Field(default=None, alias="accountNumber")
    branch_code: Optional[StrictStr] = Field(default=None, alias="branchCode")
    swift_code: Optional[StrictStr] = Field(default=None, alias="swiftCode")
    certificate_of_incorporation: Optional[StrictStr] = Field(default=None, alias="certificateOfIncorporation")
    identity_documents: Optional[StrictStr] = Field(default=None, description="JSON/text representation of identity documents", alias="identityDocuments")
    bank_account_confirmation_letter: Optional[StrictStr] = Field(default=None, alias="bankAccountConfirmationLetter")
    proof_of_business_address: Optional[StrictStr] = Field(default=None, alias="proofOfBusinessAddress")
    terms_accepted: Optional[StrictBool] = Field(default=None, alias="termsAccepted")
    accepted_at: Optional[datetime] = Field(default=None, alias="acceptedAt")
    current_step: Optional[StrictStr] = Field(default=None, alias="currentStep")
    status: Optional[StrictStr] = None
    is_completed: Optional[StrictBool] = Field(default=None, alias="isCompleted")
    completion_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="completionScore")
    __properties: ClassVar[List[str]] = ["organizationId", "companyRegistrationName", "companyRegistrationNumber", "companyTradingName", "vatRegistrationNumber", "industry", "subIndustry", "estimatedAnnualTurnover", "businessDescription", "companyMobileMoneySettlementNumber", "companyEmail", "companyContactNumber", "website", "socialMedia", "accountContactNumber", "customerSupportContactNumber", "customerSupportEscalationContactNumber", "emergencyContactNumber", "streetAddress", "apartment", "suburb", "city", "postalCode", "country", "bank", "accountType", "accountName", "accountNumber", "branchCode", "swiftCode", "certificateOfIncorporation", "identityDocuments", "bankAccountConfirmationLetter", "proofOfBusinessAddress", "termsAccepted", "acceptedAt", "currentStep", "status", "isCompleted", "completionScore"]

    @field_validator('current_step')
    def current_step_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['initiation', 'verification', 'business_details', 'banking_details', 'upload_documents', 'sign_agreement']):
            raise ValueError("must be one of enum values ('initiation', 'verification', 'business_details', 'banking_details', 'upload_documents', 'sign_agreement')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'verified', 'rejected']):
            raise ValueError("must be one of enum values ('pending', 'verified', 'rejected')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrganizationComplianceDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrganizationComplianceDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organizationId": obj.get("organizationId"),
            "companyRegistrationName": obj.get("companyRegistrationName"),
            "companyRegistrationNumber": obj.get("companyRegistrationNumber"),
            "companyTradingName": obj.get("companyTradingName"),
            "vatRegistrationNumber": obj.get("vatRegistrationNumber"),
            "industry": obj.get("industry"),
            "subIndustry": obj.get("subIndustry"),
            "estimatedAnnualTurnover": obj.get("estimatedAnnualTurnover"),
            "businessDescription": obj.get("businessDescription"),
            "companyMobileMoneySettlementNumber": obj.get("companyMobileMoneySettlementNumber"),
            "companyEmail": obj.get("companyEmail"),
            "companyContactNumber": obj.get("companyContactNumber"),
            "website": obj.get("website"),
            "socialMedia": obj.get("socialMedia"),
            "accountContactNumber": obj.get("accountContactNumber"),
            "customerSupportContactNumber": obj.get("customerSupportContactNumber"),
            "customerSupportEscalationContactNumber": obj.get("customerSupportEscalationContactNumber"),
            "emergencyContactNumber": obj.get("emergencyContactNumber"),
            "streetAddress": obj.get("streetAddress"),
            "apartment": obj.get("apartment"),
            "suburb": obj.get("suburb"),
            "city": obj.get("city"),
            "postalCode": obj.get("postalCode"),
            "country": obj.get("country"),
            "bank": obj.get("bank"),
            "accountType": obj.get("accountType"),
            "accountName": obj.get("accountName"),
            "accountNumber": obj.get("accountNumber"),
            "branchCode": obj.get("branchCode"),
            "swiftCode": obj.get("swiftCode"),
            "certificateOfIncorporation": obj.get("certificateOfIncorporation"),
            "identityDocuments": obj.get("identityDocuments"),
            "bankAccountConfirmationLetter": obj.get("bankAccountConfirmationLetter"),
            "proofOfBusinessAddress": obj.get("proofOfBusinessAddress"),
            "termsAccepted": obj.get("termsAccepted"),
            "acceptedAt": obj.get("acceptedAt"),
            "currentStep": obj.get("currentStep"),
            "status": obj.get("status"),
            "isCompleted": obj.get("isCompleted"),
            "completionScore": obj.get("completionScore")
        })
        return _obj


