# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class DebitReturnResponseDto(BaseModel):
    """
    DebitReturnResponseDto
    """ # noqa: E501
    status: StrictStr = Field(description="Payment status after 3DS authentication")
    merchant_reference: StrictStr = Field(description="Merchant reference for the payment", alias="merchantReference")
    payment_intent_id: Optional[StrictStr] = Field(default=None, description="Payment intent ID", alias="paymentIntentId")
    transaction_id: Optional[StrictStr] = Field(default=None, description="Transaction ID if payment succeeded", alias="transactionId")
    auth_code: Optional[StrictStr] = Field(default=None, description="Authorization code from payment gateway", alias="authCode")
    reason: Optional[StrictStr] = Field(default=None, description="Reason for failure if payment failed")
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Payment amount in smallest currency unit")
    currency: Optional[StrictStr] = Field(default=None, description="Currency code")
    __properties: ClassVar[List[str]] = ["status", "merchantReference", "paymentIntentId", "transactionId", "authCode", "reason", "amount", "currency"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['succeeded', 'failed', 'pending']):
            raise ValueError("must be one of enum values ('succeeded', 'failed', 'pending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebitReturnResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebitReturnResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "merchantReference": obj.get("merchantReference"),
            "paymentIntentId": obj.get("paymentIntentId"),
            "transactionId": obj.get("transactionId"),
            "authCode": obj.get("authCode"),
            "reason": obj.get("reason"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency")
        })
        return _obj


