# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EvervaultEncryptedCardDto(BaseModel):
    """
    EvervaultEncryptedCardDto
    """ # noqa: E501
    pan: StrictStr = Field(description="Encrypted Primary Account Number (PAN)", alias="PAN")
    expiry_date: StrictStr = Field(description="Encrypted card expiry date", alias="ExpiryDate")
    card_security_code: StrictStr = Field(description="Encrypted card security code (CVV)", alias="CardSecurityCode")
    cardholder_name: Optional[StrictStr] = Field(default=None, description="Encrypted cardholder name", alias="CardholderName")
    __properties: ClassVar[List[str]] = ["PAN", "ExpiryDate", "CardSecurityCode", "CardholderName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EvervaultEncryptedCardDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EvervaultEncryptedCardDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "PAN": obj.get("PAN"),
            "ExpiryDate": obj.get("ExpiryDate"),
            "CardSecurityCode": obj.get("CardSecurityCode"),
            "CardholderName": obj.get("CardholderName")
        })
        return _obj


