# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.7.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cashful.models.evervault_encrypted_card_dto import EvervaultEncryptedCardDto
from typing import Optional, Set
from typing_extensions import Self

class InitiatePaymentDto(BaseModel):
    """
    InitiatePaymentDto
    """ # noqa: E501
    amount: Union[StrictFloat, StrictInt] = Field(description="Payment amount in the smallest currency unit (e.g., cents)")
    currency: StrictStr = Field(description="Three-letter ISO 4217 currency code")
    merchant_id: StrictStr = Field(description="The unique identifier of the merchant", alias="merchantId")
    evervault_encrypted_card: EvervaultEncryptedCardDto = Field(description="Evervault encrypted card details", alias="evervaultEncryptedCard")
    payment_intent_id: Optional[StrictStr] = Field(default=None, description="Payment intent ID (generated if not provided)", alias="paymentIntentId")
    masked_pan: Optional[StrictStr] = Field(default=None, description="Masked PAN for display purposes", alias="maskedPan")
    tokenize_card: Optional[StrictBool] = Field(default=False, description="Whether to tokenize the card for future use", alias="tokenizeCard")
    first_name: Optional[StrictStr] = Field(default=None, description="Cardholder first name", alias="firstName")
    last_name: Optional[StrictStr] = Field(default=None, description="Cardholder last name", alias="lastName")
    phone_number: Optional[StrictStr] = Field(default=None, description="Cardholder phone number", alias="phoneNumber")
    payment_description: Optional[StrictStr] = Field(default=None, description="Payment description", alias="paymentDescription")
    merchant_name: Optional[StrictStr] = Field(default=None, description="Merchant name for display", alias="merchantName")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional metadata")
    __properties: ClassVar[List[str]] = ["amount", "currency", "merchantId", "evervaultEncryptedCard", "paymentIntentId", "maskedPan", "tokenizeCard", "firstName", "lastName", "phoneNumber", "paymentDescription", "merchantName", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InitiatePaymentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of evervault_encrypted_card
        if self.evervault_encrypted_card:
            _dict['evervaultEncryptedCard'] = self.evervault_encrypted_card.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InitiatePaymentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "merchantId": obj.get("merchantId"),
            "evervaultEncryptedCard": EvervaultEncryptedCardDto.from_dict(obj["evervaultEncryptedCard"]) if obj.get("evervaultEncryptedCard") is not None else None,
            "paymentIntentId": obj.get("paymentIntentId"),
            "maskedPan": obj.get("maskedPan"),
            "tokenizeCard": obj.get("tokenizeCard") if obj.get("tokenizeCard") is not None else False,
            "firstName": obj.get("firstName"),
            "lastName": obj.get("lastName"),
            "phoneNumber": obj.get("phoneNumber"),
            "paymentDescription": obj.get("paymentDescription"),
            "merchantName": obj.get("merchantName"),
            "metadata": obj.get("metadata")
        })
        return _obj


