# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.9.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class InternalAnalyticsInsightsDto(BaseModel):
    """
    InternalAnalyticsInsightsDto
    """ # noqa: E501
    organizations: Union[StrictFloat, StrictInt] = Field(description="Total number of organizations on the platform")
    customers: Union[StrictFloat, StrictInt] = Field(description="Total number of active customers across all organizations")
    saved_payment_methods: Union[StrictFloat, StrictInt] = Field(description="Total number of saved payment methods across all customers (non-deleted)", alias="savedPaymentMethods")
    transactions: Union[StrictFloat, StrictInt] = Field(description="Total number of transactions across all organizations")
    total_available_balance: Union[StrictFloat, StrictInt] = Field(description="Sum of available merchant balances across all organizations (in cents/smallest unit)", alias="totalAvailableBalance")
    total_pending_balance: Union[StrictFloat, StrictInt] = Field(description="Sum of pending merchant balances across all organizations (in cents/smallest unit)", alias="totalPendingBalance")
    __properties: ClassVar[List[str]] = ["organizations", "customers", "savedPaymentMethods", "transactions", "totalAvailableBalance", "totalPendingBalance"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InternalAnalyticsInsightsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InternalAnalyticsInsightsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organizations": obj.get("organizations"),
            "customers": obj.get("customers"),
            "savedPaymentMethods": obj.get("savedPaymentMethods"),
            "transactions": obj.get("transactions"),
            "totalAvailableBalance": obj.get("totalAvailableBalance"),
            "totalPendingBalance": obj.get("totalPendingBalance")
        })
        return _obj


