# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JwkDto(BaseModel):
    """
    JwkDto
    """ # noqa: E501
    kid: StrictStr = Field(description="Key ID uniquely identifying the key")
    kty: StrictStr = Field(description="Key type (e.g., 'RSA', 'EC', 'OKP')")
    alg: StrictStr = Field(description="Algorithm intended for use with the key")
    use: Optional[StrictStr] = Field(default=None, description="Intended use of the public key")
    n: Optional[StrictStr] = Field(default=None, description="Modulus for RSA keys")
    e: Optional[StrictStr] = Field(default=None, description="Exponent for RSA keys")
    crv: Optional[StrictStr] = Field(default=None, description="Curve name for elliptic curve keys")
    x: Optional[StrictStr] = Field(default=None, description="X coordinate for elliptic curve keys")
    y: Optional[StrictStr] = Field(default=None, description="Y coordinate for elliptic curve keys")
    __properties: ClassVar[List[str]] = ["kid", "kty", "alg", "use", "n", "e", "crv", "x", "y"]

    @field_validator('use')
    def use_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sig']):
            raise ValueError("must be one of enum values ('sig')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JwkDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if use (nullable) is None
        # and model_fields_set contains the field
        if self.use is None and "use" in self.model_fields_set:
            _dict['use'] = None

        # set to None if n (nullable) is None
        # and model_fields_set contains the field
        if self.n is None and "n" in self.model_fields_set:
            _dict['n'] = None

        # set to None if e (nullable) is None
        # and model_fields_set contains the field
        if self.e is None and "e" in self.model_fields_set:
            _dict['e'] = None

        # set to None if crv (nullable) is None
        # and model_fields_set contains the field
        if self.crv is None and "crv" in self.model_fields_set:
            _dict['crv'] = None

        # set to None if x (nullable) is None
        # and model_fields_set contains the field
        if self.x is None and "x" in self.model_fields_set:
            _dict['x'] = None

        # set to None if y (nullable) is None
        # and model_fields_set contains the field
        if self.y is None and "y" in self.model_fields_set:
            _dict['y'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JwkDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kid": obj.get("kid"),
            "kty": obj.get("kty"),
            "alg": obj.get("alg"),
            "use": obj.get("use"),
            "n": obj.get("n"),
            "e": obj.get("e"),
            "crv": obj.get("crv"),
            "x": obj.get("x"),
            "y": obj.get("y")
        })
        return _obj


