# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PaymentLinkResponseDto(BaseModel):
    """
    PaymentLinkResponseDto
    """ # noqa: E501
    id: StrictStr
    merchant_id: StrictStr = Field(alias="merchantId")
    url: StrictStr
    product_id: Optional[StrictStr] = Field(default=None, alias="productId")
    customer_id: Optional[StrictStr] = Field(default=None, alias="customerId")
    amount: Optional[Union[StrictFloat, StrictInt]] = None
    currency: StrictStr
    mode: StrictStr
    active: StrictBool
    success_url: StrictStr = Field(alias="successUrl")
    cancel_url: StrictStr = Field(alias="cancelUrl")
    metadata: Dict[str, Any]
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    deleted_at: Optional[datetime] = Field(default=None, alias="deletedAt")
    __properties: ClassVar[List[str]] = ["id", "merchantId", "url", "productId", "customerId", "amount", "currency", "mode", "active", "successUrl", "cancelUrl", "metadata", "createdAt", "updatedAt", "deletedAt"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['payment', 'setup', 'subscription']):
            raise ValueError("must be one of enum values ('payment', 'setup', 'subscription')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentLinkResponseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentLinkResponseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "merchantId": obj.get("merchantId"),
            "url": obj.get("url"),
            "productId": obj.get("productId"),
            "customerId": obj.get("customerId"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency"),
            "mode": obj.get("mode"),
            "active": obj.get("active"),
            "successUrl": obj.get("successUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "metadata": obj.get("metadata"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "deletedAt": obj.get("deletedAt")
        })
        return _obj


