# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SendEmailDto(BaseModel):
    """
    SendEmailDto
    """ # noqa: E501
    to: Dict[str, Any] = Field(description="Recipient email address(es)")
    subject: StrictStr = Field(description="Email subject")
    template: Optional[StrictStr] = Field(default=None, description="Template name to use (if using templates)")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Context variables for template rendering")
    html: Optional[StrictStr] = Field(default=None, description="HTML content (if not using templates)")
    text: Optional[StrictStr] = Field(default=None, description="Plain text content")
    var_from: Optional[StrictStr] = Field(default=None, description="Sender email address", alias="from")
    cc: Optional[Dict[str, Any]] = Field(default=None, description="CC email address(es)")
    bcc: Optional[Dict[str, Any]] = Field(default=None, description="BCC email address(es)")
    __properties: ClassVar[List[str]] = ["to", "subject", "template", "context", "html", "text", "from", "cc", "bcc"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendEmailDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendEmailDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "to": obj.get("to"),
            "subject": obj.get("subject"),
            "template": obj.get("template"),
            "context": obj.get("context"),
            "html": obj.get("html"),
            "text": obj.get("text"),
            "from": obj.get("from"),
            "cc": obj.get("cc"),
            "bcc": obj.get("bcc")
        })
        return _obj


