# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.6.1
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SignUpDto(BaseModel):
    """
    SignUpDto
    """ # noqa: E501
    name: StrictStr = Field(description="The name of the user")
    email: StrictStr = Field(description="The email address of the user")
    password: StrictStr = Field(description="The password for the user account")
    image: Optional[StrictStr] = Field(default=None, description="Optional URL to the user's profile image")
    callback_url: Optional[StrictStr] = Field(default=None, description="Optional callback URL after successful sign-up", alias="callbackURL")
    remember_me: Optional[StrictBool] = Field(default=None, description="Optional flag to indicate if the user should be remembered", alias="rememberMe")
    __properties: ClassVar[List[str]] = ["name", "email", "password", "image", "callbackURL", "rememberMe"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SignUpDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SignUpDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "password": obj.get("password"),
            "image": obj.get("image"),
            "callbackURL": obj.get("callbackURL"),
            "rememberMe": obj.get("rememberMe")
        })
        return _obj


