# coding: utf-8

"""
    Cashful API

    Developer documentation for the Cashful platform.

    The version of the OpenAPI document: 0.8.0
    Contact: support@cashful.africa
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cashful.models.hosted_checkout_config_dto import HostedCheckoutConfigDto
from typing import Optional, Set
from typing_extensions import Self

class UpdatePaymentLinkDto(BaseModel):
    """
    UpdatePaymentLinkDto
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="The name of the payment link")
    description: Optional[StrictStr] = Field(default=None, description="A description of the payment link")
    active: Optional[StrictBool] = Field(default=None, description="Whether the payment link is active")
    total_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalAmount")
    success_url: Optional[StrictStr] = Field(default=None, description="The URL to redirect to on successful payment", alias="successUrl")
    cancel_url: Optional[StrictStr] = Field(default=None, description="The URL to redirect to if customer cancels", alias="cancelUrl")
    metadata: Dict[str, Any] = Field(description="Optional custom metadata")
    hosted_checkout_config: Optional[HostedCheckoutConfigDto] = Field(default=None, description="Configuration for the hosted checkout page", alias="hostedCheckoutConfig")
    __properties: ClassVar[List[str]] = ["name", "description", "active", "totalAmount", "successUrl", "cancelUrl", "metadata", "hostedCheckoutConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdatePaymentLinkDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hosted_checkout_config
        if self.hosted_checkout_config:
            _dict['hostedCheckoutConfig'] = self.hosted_checkout_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdatePaymentLinkDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "active": obj.get("active"),
            "totalAmount": obj.get("totalAmount"),
            "successUrl": obj.get("successUrl"),
            "cancelUrl": obj.get("cancelUrl"),
            "metadata": obj.get("metadata"),
            "hostedCheckoutConfig": HostedCheckoutConfigDto.from_dict(obj["hostedCheckoutConfig"]) if obj.get("hostedCheckoutConfig") is not None else None
        })
        return _obj


